package com.rendox.routinetracker.core.ui.theme

import androidx.compose.ui.graphics.Color

// Paleta do app: indigo profundo como cor principal e verde-agua como acento.
// A ideia e passar calma e foco, em vez do azul generico de sistema.

val md_theme_light_primary = Color(0xFF4B3FD1)
val md_theme_light_onPrimary = Color(0xFFFFFFFF)
val md_theme_light_primaryContainer = Color(0xFFE3DFFF)
val md_theme_light_onPrimaryContainer = Color(0xFF150067)
val md_theme_light_secondary = Color(0xFF5E5C71)
val md_theme_light_onSecondary = Color(0xFFFFFFFF)
val md_theme_light_secondaryContainer = Color(0xFFE4E0F9)
val md_theme_light_onSecondaryContainer = Color(0xFF1B1A2C)
val md_theme_light_tertiary = Color(0xFF00695B)
val md_theme_light_onTertiary = Color(0xFFFFFFFF)
val md_theme_light_tertiaryContainer = Color(0xFF7DF8DC)
val md_theme_light_onTertiaryContainer = Color(0xFF00201A)
val md_theme_light_error = Color(0xFFB3261E)
val md_theme_light_errorContainer = Color(0xFFFFDAD6)
val md_theme_light_onError = Color(0xFFFFFFFF)
val md_theme_light_onErrorContainer = Color(0xFF410E0B)
val md_theme_light_background = Color(0xFFFBF8FF)
val md_theme_light_onBackground = Color(0xFF1B1B21)
val md_theme_light_surface = Color(0xFFFBF8FF)
val md_theme_light_onSurface = Color(0xFF1B1B21)
val md_theme_light_surfaceVariant = Color(0xFFE4E1EC)
val md_theme_light_onSurfaceVariant = Color(0xFF47464F)
val md_theme_light_outline = Color(0xFF787680)
val md_theme_light_inverseOnSurface = Color(0xFFF3EFF7)
val md_theme_light_inverseSurface = Color(0xFF303036)
val md_theme_light_inversePrimary = Color(0xFFC5C0FF)
val md_theme_light_surfaceTint = Color(0xFF4B3FD1)
val md_theme_light_outlineVariant = Color(0xFFC8C5D0)
val md_theme_light_scrim = Color(0xFF000000)

val md_theme_dark_primary = Color(0xFFC5C0FF)
val md_theme_dark_onPrimary = Color(0xFF2300A0)
val md_theme_dark_primaryContainer = Color(0xFF3826B8)
val md_theme_dark_onPrimaryContainer = Color(0xFFE3DFFF)
val md_theme_dark_secondary = Color(0xFFC8C3DC)
val md_theme_dark_onSecondary = Color(0xFF302E42)
val md_theme_dark_secondaryContainer = Color(0xFF464459)
val md_theme_dark_onSecondaryContainer = Color(0xFFE4E0F9)
val md_theme_dark_tertiary = Color(0xFF5FDBC0)
val md_theme_dark_onTertiary = Color(0xFF00382F)
val md_theme_dark_tertiaryContainer = Color(0xFF005045)
val md_theme_dark_onTertiaryContainer = Color(0xFF7DF8DC)
val md_theme_dark_error = Color(0xFFFFB4AB)
val md_theme_dark_errorContainer = Color(0xFF93000A)
val md_theme_dark_onError = Color(0xFF690005)
val md_theme_dark_onErrorContainer = Color(0xFFFFDAD6)
val md_theme_dark_background = Color(0xFF131318)
val md_theme_dark_onBackground = Color(0xFFE5E1E9)
val md_theme_dark_surface = Color(0xFF131318)
val md_theme_dark_onSurface = Color(0xFFE5E1E9)
val md_theme_dark_surfaceVariant = Color(0xFF47464F)
val md_theme_dark_onSurfaceVariant = Color(0xFFC8C5D0)
val md_theme_dark_outline = Color(0xFF928F9A)
val md_theme_dark_inverseOnSurface = Color(0xFF131318)
val md_theme_dark_inverseSurface = Color(0xFFE5E1E9)
val md_theme_dark_inversePrimary = Color(0xFF4B3FD1)
val md_theme_dark_surfaceTint = Color(0xFFC5C0FF)
val md_theme_dark_outlineVariant = Color(0xFF47464F)
val md_theme_dark_scrim = Color(0xFF000000)

val routine_status_light_completed_stroke = Color(0xFF2E7D32)
val routine_status_light_completed_background = Color(0xFF81C784)
val routine_status_light_skipped_in_streak = Color(0xFFD7E8D4)
val routine_status_light_failed_stroke = Color(0xFFC53A5E)
val routine_status_light_failed_background = Color(0xFFDB879E)
val routine_status_light_skipped_out_of_streak = Color(0xFFF1D5DF)
val routine_status_light_vacation_stroke = Color(0xFFD99417)
val routine_status_light_vacation_background = Color(0xFFE7BD74)

val routine_status_dark_completed_stroke = Color(0xFF6FAC44)
val routine_status_dark_completed_background = Color(0xFF337700)
val routine_status_dark_skipped_in_streak = Color(0xFF2C401E)
val routine_status_dark_failed_stroke = Color(0xFFB64E68)
val routine_status_dark_failed_background = Color(0xFF71142A)
val routine_status_dark_skipped_out_of_streak = Color(0xFF3C292F)
val routine_status_dark_vacation_stroke = Color(0xFFFFBC44)
val routine_status_dark_vacation_background = Color(0xFF865A08)
